---
title: "US CHINA TRADE"
author: "PEIZHI ZHANG, Hanyi Wang, Xinyi Shi, Huiling Zhou"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}
library(shiny)
library(leaflet)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(RCurl)
library(sqldf)
library(plotly)
library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(tm)
library(scales)
library(DT)
library(tidyverse)
library(ggrepel)
library(readr)
library(data.table)



```

```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

df <- read.csv('SETO.csv')
```

```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
  titlePanel("Solar Energy Research Database"),
  
  sidebarLayout(
    sidebarPanel(
      checkboxGroupInput(
        inputId = "SUBPROGRAM",
        label = "PROGRAM AREA",
        choices = c("Concentrating Solar Power" = "Concentrating Solar Power",
                    "Manufacturing and Competitiveness" = "Manufacturing and Competitiveness",
                    "Photovoltaics" = "Photovoltaics", 
                    "Soft Costs" = "Soft Costs",
                    "Systems Integration" = "Systems Integration"
					),
        selected = c("Concentrating Solar Power",
                     "Manufacturing and Competitiveness",
                     "Photovoltaics", 
                     "Soft Costs",
                     "Systems Integration"
        ),
		),
	
      selectInput(
        inputId = "Status",
        label = "STATUS",
    		choices = c("Any" = "Any",
    		            "Active" = "Active",
                    "Inactive" = "Inactive"
					),
        selected = "Any"
      ),
	  
      selectInput(
        inputId = "FOA_Acronym",
        label = "FUNDING OPPORTUNITY",
        choices = c("All" = "All",
                    "AOP" = "AOP",
                    "AOP 13-15" = "AOP 13-15",
                    "AOP 2015" = "AOP 2015",
                    "AOP 2016" = "AOP 2016",
                    "ASSIST" = "ASSIST",
                    "Bos-X" = "Bos-X",
                    "BRIDGE" = "BRIDGE",
                    "BTMS" = "BTMS",
                    "CSP 2012 Lab Call" = "CSP 2012 Lab Call",
                    "CSP APOLLO" = "CSP APOLLO",
                    "CSP ARRA" = "CSP ARRA",
                    "CSP Baseload" = "CSP Baseload",
                    "CSP COLLECTS" = "CSP COLLECTS",
                    "CSP HIBRED" = "CSP HIBRED",
                    "CSP Lab Call" = "CSP Lab Call",
                    "CSP R&D" = "CSP R&D",
                    "CSP SunShot R&D" = "CSP SunShot R&D",
                    "Desal" = "Desal",
                    "DISTANCE" = "DISTANCE",
                    "DuraMat" = "DuraMat",
                    "ELEMENTS" = "ELEMENTS",
                    "EMPOWERED" = "EMPOWERED",
                    "ENERGISE" = "ENERGISE",
                    "Engineering Research Centers" = "Engineering Research Centers",
                    "Forecasting 2" = "Forecasting 2",
                    "F-PACE" = "F-PACE",
                    "F-PACE 2" = "F-PACE 2",
                    "FY20 PVSK" = "FY20 PVSK",
                    "FY21 PV & CSP" = "FY21 PV & CSP",
                    "FY21 SI & Incubator" = "FY21 SI & Incubator",
                    "FY22 CSP" = "FY22 CSP",
                    "FY22 SIPS - CSP & PV" = "FY22 SIPS - CSP & PV",
                    "GEARED" = "GEARED",
                    "Gen3 CSP" = "Gen3 CSP",
                    "Gen3 CSP Lab Call" = "Gen3 CSP Lab Call",
                    "General AOP" = "General AOP",
                    "GMLC-GM" = "GMLC-GM",
                    "GMLC-RDS" = "GMLC-RDS",
                    "High Pen" = "High Pen",
                    "Incubator 1" = "Incubator 1",
                    "Incubator 2" = "Incubator 2",
                    "Incubator 3" = "Incubator 3",
                    "Incubator 4" = "Incubator 4",
                    "Incubator 5" = "Incubator 5",
                    "Incubator 6" = "Incubator 6",
                    "Incubator 7" = "Incubator 7",
                    "Incubator 8" = "Incubator 8",
                    "Incubator 9" = "Incubator 9",
                    "Innovative Pathways" = "Innovative Pathways",
                    "JIT" = "JIT",
                    "Lab Call 19-21" = "Lab Call 19-21",
                    "Lab Call FY20" = "Lab Call FY20",
                    "Lab Call FY21" = "Lab Call FY21",
                    "Lab Call FY22-24" = "Lab Call FY22-24",
                    "Lab Core FY21" = "Lab Core FY21",
                    "Mini-SuNLaMP" = "Mini-SuNLaMP",
                    "MURA" = "MURA",
                    "MURI" = "MURI",
                    "NextGen 2" = "NextGen 2",
                    "NextGen 3" = "NextGen 4",
                    "Orange Button" = "Orange Button",
                    "Plug and Play" = "Plug and Play", 
                    "Power Electronics" = "Power Electronics",
                    "PREDICTS" = "PREDICTS",
                    "PREDICTS 2" = "PREDICTS 2",
                    "Pre-Incubator" = "Pre-Incubator",
                    "PUC" = "PUC",
                    "PV Lifetime" = "PV Lifetime",
                    "PVMI" = "PVMI",
                    "PVRD SIPS" = "PVRD SIPS",
                    "PVRD" = "PVRD",
                    "PVRD2" = "PVRD2",
                    "Rooftop Solar Challenge" = "Rooftop Solar Challenge",
                    "Rooftop Solar Challenge 2" = "Rooftop Solar Challenge 2",
                    "RTC" = "RTC",
                    "RACER" = "RACER",
                    "SBIR/STTR FY11" = "SBIR/STTR FY11",
                    "SBIR/STTR FY12" = "SBIR/STTR FY12",
                    "SBIR/STTR FY13" = "SBIR/STTR FY13",
                    "SBIR/STTR FY14" = "SBIR/STTR FY14",
                    "SBIR/STTR FY15" = "SBIR/STTR FY15",
                    "SBIR/STTR FY16" = "SBIR/STTR FY16",
                    "SBIR/STTR FY17" = "SBIR/STTR FY17",
                    "SBIR/STTR FY18" = "SBIR/STTR FY18",
                    "SBIR/STTR FY19" = "SBIR/STTR FY19",
                    "SBIR/STTR FY20" = "SBIR/STTR FY20",
                    "SBIR/STTR FY21 PI R2" = "SBIR/STTR FY21 PI R2",
                    "SBV-1" = "SBV-1",
                    "SBV-2" = "SBV-2",
                    "SBV-3" = "SBV-3",
                    "SEEDS" = "SEEDS",
                    "SEEDS2-SES" = "SEEDS2-SES",
                    "SEGIS-AC" = "SEGIS-AC",
                    "SEIN" = "SEIN",
                    "SETO FY2018" = "SETO FY2018",
                    "SETO FY2019" = "SETO FY2019",
                    "SETO FY2020" = "SETO FY2020",
                    "SHINES" = "SHINES",
                    "Soft BOS" = "Soft BOS",
                    "Solar America Cities" = "Solar America Cities",
                    "Solar Forecasting" = "Solar Forecasting",
                    "SolarOps" = "SolarOps",
                    "SolarMat" = "SolarMat",
                    "SolarMat 2" = "SolarMat 2",
                    "Solar Market Pathways" = "Solar Market Pathways",
                    "SPARC" = "SPARC",
                    "STEP" = "STEP",
                    "SolWEB" = "SolWEB",
                    "SunPath" = "SunPath",
                    "SunShot Prize" = "SunShot Prize",
                    "SuNLaMP" = "SuNLaMP",
                    "SUNRISE" = "SUNRISE",
                    "T2M 1" = "T2M 1",
                    "T2M 2" = "T2M 2",
                    "T2M 3" = "T2M 3",
                    "TCF FY16" = "TCF FY16",
                    "TCF FY17" = "TCF FY17",
                    "TCF FY18" = "TCF FY18",
                    "TCF FY19" = "TCF FY19",
                    "TCF FY20" = "TCF FY20",
                    "TCF FY21" = "TCF FY21",	
                    "Thermal Storage" = "Thermal Storage",
                    "VELOCITI" = "VELOCITI"
					),
        selected = "All")
		
      ),
    
    mainPanel(
      leafletOutput("USA")
    )
  )
  
  
  
)
```

```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

# DEFINE SERVER LOGIC ---------------------------------------------------------------
server <- function(input, output) {
  
  output$USA <- renderLeaflet({
    df_leaf <-
      df %>%
      filter(Status == input$Status,
             FOA_Acronym == input$FOA_Acronym,
			       SUBPROGRAM == input$SUBPROGRAM)
    #write.csv(df_leaf, file="df_leaf.csv", row.names = FALSE)
    leaflet(df_leaf) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addMarkers(~Longitude,~Latitude,popup = ~Status,clusterOptions = markerClusterOptions())%>%
	    addMarkers(~Longitude,~Latitude,popup = ~FOA_Acronym,clusterOptions = markerClusterOptions())%>%
      addMarkers(~Longitude,~Latitude,popup = ~SUBPROGRAM,clusterOptions = markerClusterOptions())%>%
      addSearchOSM() %>%
      addMiniMap()     
    
  })
  
}
```

```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

shinyApp(ui = ui, server = server)


```





```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

CN_US_cleaned_all <- read.csv("CN_US_cleaned_all.csv")
subset <- CN_US_cleaned_all[grep("^8541", CN_US_cleaned_all$HS6code),]


plot_data <- subset %>%
  group_by(period) %>%
  summarise(total_balance_primaryvalue = sum(balance_primaryValue),
            total_balance_qty = sum(balance_qty)) %>%
  mutate(primary_value_label = paste("Period: ", period, "<br> Balance Primary Value: ",
                                     round(total_balance_primaryvalue*10^(-3),2), " (thousands USD)"),
         qty_label = paste("Period: ", period, "<br> Balance Quantity: ",
                            round(total_balance_qty*10^(-4), 2), " (ten thousands units)"))

plot1 <- ggplot(plot_data, aes(x = period)) +
  geom_line(aes(y = total_balance_primaryvalue*10^(-3), color = "Total Balance Primary Value (thousands USD)"), size = 1.5) +
  geom_point(aes(y = total_balance_primaryvalue*10^(-3), color = "Total Balance Primary Value (thousands USD)", text = primary_value_label), size = 3) +
  geom_line(aes(y = total_balance_qty*10^(-4), color = "Total Balance Quantity (ten thousands units)"), size = 1.5) +
  geom_point(aes(y = total_balance_qty*10^(-4), color = "Total Balance Quantity (ten thousands units)", text = qty_label), size = 3) +
  scale_color_manual(values = c("green", "blue")) +
  scale_y_continuous(name = "Total Balance", labels = scales::comma) +
  labs(x = "Year", y = "Total balance primary value (thousands USD)") +
  ggtitle("China vs. US: Balance Primary Value and Quantity per Year(2017-21)") +
  theme_minimal() +
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 18),
        panel.grid.major = element_line(color = "gray", linetype = "dashed"),
        legend.position = "bottom",
        legend.direction = "vertical") +
  labs(caption = "Source: CN_US_cleaned_all dataset")
  

plotly_fig <- ggplotly(plot1, tooltip = c("text"), colors = c("Total Balance Primary Value (thousands USD)" = "green", "Total Balance Quantity (ten thousands units)" = "blue"))

plotly_fig <- plotly_fig %>% layout(legend = list(x = 0.2, y = -0.4))

plotly_fig


```





```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

setwd("/Users/peizhi/Documents/Data Visualization/")

file_paths <- list.files("tradetext", pattern = ".txt", full.names = TRUE)

tradedata <- lapply(file_paths, readLines) %>% unlist() %>% data.frame(text = .)


```



```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

library(tm)
library(SnowballC)
library(wordcloud)
library(tidytext)
library(tidyverse)

new_stops <- c("room","one","stop","minutes","nearby","listing","br","equipped","building","just","can","size","prior","welcome","ave","away","will","aside","except","month","home","bedroom","bathroom","two","three","apartment","unit","area","'ll","place","located","blocks","couple","plus","restaurants","shops","must","like","surrounded","daily","will","provide","without","within","spacebbr","bthe","nycbr","nyc","years","looking","information","give","makes","street","ny","city","quite","come","also","likebr","people","giving","five","behind","need","allow","space","next","world","stay","single","kitchen","guest","ride","min","citi","cit", "cinemat", "cinco", "chunk","circl","access","accessbbr","accomodation","accomod","air","amaz","footnote","citation","moreover",
               "beside","on","also","including","if","article","then","likely","such","as","requires",
               "Chinese", "youre", "present", "past", "Chinas", "China's", "India", "number", "Maria", "Although", 
               "studies","solar","energy","hence","third","section","study",
               "yesterday","comes","thank","earlier","came","doc","talk","tell","found","part","way",
               "thats","therefore","energies","yet","morning","done","theyre","bri","suggests","lets",
               "taking","believe","job","Chinese","China","trade", "think","know","much",
               "said","however","second","thus","country", "china", "market","industry","United","States","chinese","countries",
               stopwords("en"))

data_corpus <- VCorpus(VectorSource(tradedata$text))
data_corpus <- tm_map(data_corpus, removePunctuation)
data_corpus <- tm_map(data_corpus, content_transformer(tolower))
data_corpus <- tm_map(data_corpus, stripWhitespace)
data_corpus <- tm_map(data_corpus, removeWords, stopwords("english"))
data_corpus <- tm_map(data_corpus, removeWords, c(new_stops))
data_corpus <- tm_map(data_corpus, removeNumbers)

```



## Word Cloud 


```{r, message = FALSE, warning = FALSE, error=FALSE, echo=FALSE}

dtm <- DocumentTermMatrix(data_corpus)

word_freq <- colSums(as.matrix(dtm))

word_freq_df <- data.frame(word = names(word_freq), freq = word_freq)

wordcloud(words = word_freq_df$word, freq = word_freq_df$freq, min.freq = 5, max.words = 200,
          colors=c("green","blue"))

```




